//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoalaInterFaceModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_File_TemplateInfo
    {
        public int ID { get; set; }
        public string MTS_T_ID { get; set; }
        public string MTS_T_Name { get; set; }
        public Nullable<int> MTS_T_Type { get; set; }
        public string T_Description { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> bUsed { get; set; }
        public string FileSuffix { get; set; }
        public Nullable<int> SortNum { get; set; }
    }
}
