//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoalaInterFaceModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BG_RequestMTS_FileInfo
    {
        public int ID { get; set; }
        public string Guid { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> FileType { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> TableID { get; set; }
        public string FilePic { get; set; }
        public Nullable<int> bUsed { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public string VideoThumbnail { get; set; }
        public Nullable<int> AudioTime { get; set; }
    }
}
