//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoalaInterFaceModels
{
    using System;
    using System.Collections.Generic;

    public partial class BG_RequestMTS_FileInfo_Detaile
    {
        public int ID { get; set; }
        public int RID { get; set; }
        public int TID { get; set; }
        public string FilePath { get; set; }
        public string JobID { get; set; }
        public string Description { get; set; }
        public int bUsed { get; set; }
        public DateTime AddTime { get; set; }
        public string Guid { get; set; }
        public BG_File_TemplateInfo BG_File_TemplateInfo { get; }
        public BG_RequestMTS_FileInfo BG_RequestMTS_FileInfo { get; }
    }
}
