//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoalaInterFaceModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class KL_PictureBook_Info
    {
        public int id { get; set; }
        public string guid { get; set; }
        public string name { get; set; }
        public string coverImage { get; set; }
        public string thumbnail { get; set; }
        public string video { get; set; }
        public Nullable<int> beUsed { get; set; }
        public Nullable<int> MTSstatus { get; set; }
        public Nullable<int> sortId { get; set; }
        public Nullable<System.DateTime> uploadTime { get; set; }
    }
}
