//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoalaInterFaceModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KoalaKnowDevEntities : DbContext
    {
        public KoalaKnowDevEntities()
            : base("name=KoalaKnowDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BG_File_TemplateInfo> BG_File_TemplateInfo { get; set; }
        public DbSet<BG_RequestMTS_FileInfo> BG_RequestMTS_FileInfo { get; set; }
        public DbSet<BG_RequestMTS_FileInfo_Detaile> BG_RequestMTS_FileInfo_Detaile { get; set; }
        public DbSet<BG_SubPic_Error_Log> BG_SubPic_Error_Log { get; set; }
        public DbSet<KL_PictureBook_Info> KL_PictureBook_Info { get; set; }
        public DbSet<userlist> userlist { get; set; }
    }
}
