//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoalaInterFaceModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class userlist
    {
        public int id { get; set; }
        public string guid { get; set; }
        public string appid { get; set; }
        public string type { get; set; }
        public string openid { get; set; }
        public string unionid { get; set; }
        public string clientid { get; set; }
        public string nickname { get; set; }
        public string fatherName { get; set; }
        public string montherName { get; set; }
        public string sex { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string headimgurl { get; set; }
        public string mobile { get; set; }
        public string password { get; set; }
        public string baby_name { get; set; }
        public string baby_english_name { get; set; }
        public string baby_kindergarten { get; set; }
        public string baby_address { get; set; }
        public string baby_headimgurl { get; set; }
        public string baby_age { get; set; }
        public Nullable<System.DateTime> baby_brithday { get; set; }
        public string student_id { get; set; }
        public Nullable<int> agent_status { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<int> flag { get; set; }
        public string utype { get; set; }
        public Nullable<int> specialID { get; set; }
        public string vc_u_email { get; set; }
        public string vc_u_from { get; set; }
        public string nvc_u_email_type { get; set; }
        public string vc_u_email_pwd { get; set; }
        public string vc_u_facebook_id { get; set; }
        public string vc_u_facebook_name { get; set; }
        public string vc_u_facebook_mail { get; set; }
        public string vc_u_facebook_head { get; set; }
        public string nvc_u_surname { get; set; }
        public string vc_u_vChar_id { get; set; }
        public string vc_u_vChar_name { get; set; }
        public string vc_u_vChar_head { get; set; }
        public string vc_u_vChar_no { get; set; }
        public Nullable<int> i_u_vChar_status { get; set; }
        public string vc_u_Pay_Status { get; set; }
        public Nullable<int> i_u_Account_status { get; set; }
        public string nvc_baby_summary { get; set; }
    }
}
